logging:
  level:
    org.springframework: DEBUG
    com.etna.gpe.mycloseshop: DEBUG
    com.etna.gpe.mycloseshop.security_api: DEBUG
    slf4j: DEBUG
    org.springframework.security: DEBUG

rabbitmq:
  exchange:
    appointments: appointments-exchange
  queue:
    appointments:
      created: appointments-created-queue

server:
  port: ${SPRING_APP_PORT:8082}
  servlet:
    context-path: /api/ms-shop-api
spring:
  application:
    name: ms-shop-api

  cloud:
    discovery:
      enabled: true

  rabbitmq:
    port: ${SPRING_RABBITMQ_PORT:5672}
    host: ${SPRING_RABBITMQ_HOST:localhost}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3309/db-ms-shop?useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC}
    username: ${SPRING_DATASOURCE_USERNAME:user}
    password: ${SPRING_DATASOURCE_PASSWORD:secret}
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update # A modifier si besoin `create` ou `update`
    show-sql: true
    database: mysql
  main:
    allow-bean-definition-overriding: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html